### ISSUE TITLE
🐛 Postgres: Sorting for Postgres tables does not work poperly.

### ISSUE THREAD

**Issue by butschster** [cycle/database#101]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### Database

PostgreSQL

### What happened?

When Reflector starts sorting tables with dependencies https://github.com/cycle/database/blob/2.x/src/Schema/Reflector.php#L223 , depended table names don't contain table schema prefixes.

```php
array(4) {
  ["public.threads"]=>
  array(0) {
  }
  ["public.messages"]=>
  array(2) {
    [0]=>
    string(7) "threads" <===== Should be `public.threads`
    [1]=>
    string(5) "users" <===== Should be `public.threads`
  }
  ["public.users"]=>
  array(0) {
  }
  ["public.auth_tokens"]=>
  array(0) {
  }
}
```

### Version

```shell
database 2.0
PHP 8.1
```

**Comment by roxblnfk** [comment]
Fixed in v2.4.1
Thanks.
