### ISSUE TITLE
🐛 Index on FK is created despite Relation::$indexCreate=false

### ISSUE THREAD

**Issue by scapital** [cycle/database#113]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### Database

PostgreSQL

### What happened?

Even if [the options](https://github.com/cycle/annotated/blob/69f0d18e1a1c36faadc1416f2e6feb207954e7bd/src/Annotation/Relation/BelongsTo.php#L54) is false, [index](https://github.com/cycle/database/blob/457d1f2b43e676ec4fd40e94696defb15b4a6c82/src/Schema/AbstractTable.php#L450) will be created by Cycle\Schema\Generator\Migrations\GenerateMigrations

Sometimes relation db is used just like a persistence storage, with insert/select by id only operation,
not operational db, so index is unnecessary for these cases.

As a workaround, I deleted these indexes in the same migrations.
Cycle\Schema\Generator\Migrations\GenerateMigrations will not find any differences,
so it look like the bug happen only while generate migrations for new table.

### Version

```shell
database 2.4.1
PHP 8.2
```

**Comment by wapmorgan** [comment]
it was discovered firstly in #82
