### ISSUE TITLE
🐛 Memory leak on batch insert

### ISSUE THREAD

**Issue by gam6itko** [cycle/database#136]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### Database

MySQL

### What happened?

I use `DatabaseInterface::execute` to batch insert. I detect a huge memory leak if `queryCache: true`.

The problem is that the number of VALUES may differ, and each time the request is cached.

I create demo-project with demo of issue: https://github.com/gam6itko/spiral-app-sandbox/blob/cb97213a8c12f7e98ae4186d3e90f2d8b2b09bea/src/app/app/src/Command/CycleMemoryLeakCommand.php#L49

![image](https://github.com/cycle/database/assets/3841197/09b48acf-3149-4cc9-8f51-b47c6baff43e)
  

### Version

```shell
database 2.5.2
PHP 8.1
```

**Comment by roxblnfk** [comment]
Now it is available to disable driver query cache before any request.
We are thinking about automatic disabling cache in batch insert case but I'm not sure that it will be implemented.

Release is coming.

**Comment by roxblnfk** [comment]
We decided not to add heuristics to the `execute` method. Therefore, simply use the `$driver->withoutCache()` method before executing queries that do not need to be cached.
