### ISSUE TITLE
Issue with where('ball', '<',  'water')🐛 

### ISSUE THREAD

**Issue by sjaakp** [cycle/database#62]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### Database

MySQL

### What happened?

When I put a where-statement like where('ball', '<',  'water'), I'm being presented with an error like:

Type: TypeError
Code: 0
Message: strtoupper(): Argument #1 ($string) must be of type string, int given
File: D:\websites\slim.local\vendor\cycle\database\src\Query\Traits\TokenTrait.php
Line: 171

I have the impression it has something to do with the operator value of '<'. But that isn't an int, is it?

Obviously I didn't expect an error.
Or am I doing something wrong?

### Version

```shell
database 2.0
PHP 8.1
```

**Comment by sjaakp** [comment]
Sorry, I found my mistake. I wrapped where's arguments in an array... Stupid me.

**Comment by roxblnfk** [comment]
In any case, thanks for the activity :)
