### ISSUE TITLE
💡 MySQL support unsigned integer attribute

### ISSUE THREAD

**Issue by gam6itko** [cycle/database#65]
### I have an idea!

I have a DB with many columns of `int unsigned`. I want to manage this DB with cycle ORM. Required feature to mark integer columns as `unsigned`

**Comment by roxblnfk** [comment]
We need to decide witch approach is better:

https://github.com/cycle/database/pull/66
or
https://github.com/cycle/database/pull/88

**Comment by gam6itko** [comment]
Done
